version: '3.1'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pssw
    volumes:
      - mongo:/data/db
  mongoclient:
    image: mongoclient/mongoclient
    ports:
      - 4000:3000
    environment:
      MONGO_ULR: mongodb://root:pssw@mongo:27017/mongoclient?authSource=admin
      MONGOCLIENT_AUTH: "true"
      MONGOCLIENT_USERNAME: admin
      MONGOCLIENT_PASSWORD: password
      MONGOCLIENT_DEFAULT_CONNECTION_URL: mongodb://root:pssw@mongo:27017/mongo?authSource=admin
volumes:
  mongo: